apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: nginx
        image: nginx:1.15.4
        name: default-mem-demo-ctr
        resources:
          requests:
            memory: "125Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "500m"
        env:
          - name: SPECIAL_LEVEL_KEY
            valueFrom:
              configMapKeyRef:
                name: log-config
                key: log.level
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: root
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password
                key: password
      initContainers:
        - name: install
          image: busybox
          command:
          - wget
          - "-O"
          - "/work-dir/index.html"
          - http://kubernetes.io
  
#   - name: LOG_LEVEL
        
  
#         ports:
#         - containerPort: 80